### ISSUE TITLE
Navigation doesn't work on Windows 

### ISSUE THREAD

**Issue by anpin** [PrismLibrary/Prism.Maui#100]
`PrismMauiDemo` sample on `net6.0-windows` target doesn't react when `INavigationService.NavigateAsync` is called and no error is written. 

Strangely enough in another project I have at hand navigation pushes the page, but it always replaces the root `NavigationPage`, so no top bar with back button and page title is visible. 

Steps to reproduce: 
1. Build and run sample 
2.  Press on of the buttons

**Comment by dansiegel** [comment]
In order to take a big report like this I need a reproduction app. If you can provide a sample app that reproduces the issue I'll reopen the issue.

**Comment by anpin** [comment]
Hi @dansiegel thanks for the swift response, but have you read the report? It includes steps to reproduce and here is the video demonstrating the issue with provided `PrismMauiDemo` sample project

https://user-images.githubusercontent.com/6060545/183437589-9577cd9d-9554-41ee-a9ec-491311cc0b48.mp4

As for the second issue I'm still investigating the possible cause

**Comment by amaneshi** [comment]
Same, repro project just inside this repo.
