### ISSUE TITLE
PrismMauiDemo

### ISSUE THREAD

**Issue by luigicasalegno** [PrismLibrary/Prism.Maui#102]
I downloaded the demo on August 13 and built with sdk 6.0.400 and Visual Studio 17.3.0. The demo work perfectly with android devices, but it dos not seem to work at all with Windows. IN windows I managed to see some pages when I changed the absolute address with a relative one (see attached file). I hope it can help
[RootPage.txt](https://github.com/PrismLibrary/Prism.Maui/files/9332937/RootPage.txt)
p

**Comment by cnao-ctrl-dev** [comment]
if you change the following line 
.AddSegment<SplashPageViewModel>() (line 56)
with
,AddSegment<RootPageViewModel>()
in file MauiProgams.cs everything seems to work correctly.
Adding a Splash Screen in Windows does not seem to work

**Comment by dansiegel** [comment]
Please be sure to ask questions in the [Prism Discussions](https://github.com/PrismLibrary/Prism/discussions/new?category=-net-maui).
