### ISSUE TITLE
Toolbar item icons do not update when navigating back

### ISSUE THREAD

**Issue by Adam--** [PrismLibrary/Prism.Maui#104]
When navigating back from a page that includes toolbar items to a page that includes toolbar items, the toolbar item icons shown on the second page show on the first page.

### Steps to reproduce
Create an application with multiple pages, say MainPage and Page2.
Add a toolbar item to MainPage with Text.
Add a toolbar item to Page2 with an IconImageSource.

Start the application on Android.
Observe the toolbar item.
![image](https://user-images.githubusercontent.com/2179171/185666602-023ad108-c97d-40d3-8634-b5333f029645.png)

Navigate to Page2
Observe the toolbar items
![image](https://user-images.githubusercontent.com/2179171/185666676-f846218d-93c6-4dfc-8cbd-9686eea1e782.png)

Press the back button in the toolbar on Page2 to navigate back to MainPage.
Observe the toolbar item on MainPage is now the same toolbar item that was on Page2.
![image](https://user-images.githubusercontent.com/2179171/185666724-48b45d21-dcfc-47d2-8d63-a7e7994ac0d1.png)

Expected outcome: The MainPage toolbar item is the original MainPage toolbar item
Actual outcome: The MainPage toolbar item changes to the toolbar item from Page2.

### Affected platforms

Prism 8.1.273-pre

*Android* is affected
Windows is not.
I am unable to test on iOS.

I'm using Visual Studio Professional Version 17.3.1

### Reproduction project
[Prism.Maui toolbar item icons issue.zip](https://github.com/PrismLibrary/Prism.Maui/files/9383908/Prism.Maui.toolbar.item.icons.issue.zip)

This solution contains two projects MauiApp1 and PrismMauiApp2 with the same basic application described in the repro steps.
MauiApp1 is a Maui shell app. The issue _is not_ observed with this project.
PrismMauiApp2 is a Prism.Maui app. The issues _is_ observed with this project.

**Comment by Adam--** [comment]
I hope I've provided enough info for this issue, but if there's anything else I can do to help out with it, please let me know.

**Comment by dansiegel** [comment]
Sorry I wasn't able to respond sooner. This issue would be with Maui itself not with Prism. We don't handle anything specific in this area.

**Comment by Adam--** [comment]
@dansiegel No worries, I appreciate that you did respond. 

Do you have any idea why it's not an issue in a Maui shell app, but it is an issue in a Prism.Maui app?

In the attached zip, there's a solution that contains two projects MauiApp1 and PrismMauiApp2 with the same basic application described in the repro steps.
MauiApp1 is a Maui shell app. The issue **is not** observed with this project.
PrismMauiApp2 is a Prism.Maui app. The issue **is** observed with this project.

**Comment by Adam--** [comment]
Thanks for the insight. It really seems like Maui is _still_ not production ready, huh?
Thanks again.
