### ISSUE TITLE
Prism Template Pack for MAUI available?

### ISSUE THREAD

**Issue by nschoenberg** [PrismLibrary/Prism.Maui#109]
Hi,

could not find any info about Prism Template Pack for MAUI. Do you have plans to support Maui with the template pack?

Thanks in advance :)

**Comment by dansiegel** [comment]
The Template Pack is a pet project for @brianlagunas. He'll likely get to it at some point. In the mean time you can install the dotnet templates from NuGet using the dotnet cli and it should be available for you in Visual Studio & Rider... not sure about Visual Studio for Mac
