### ISSUE TITLE
Dialog Styling does not exist

### ISSUE THREAD

**Issue by nikoslyk2093** [PrismLibrary/Prism.Maui#113]
In Xamarin Forms I was using this feature to setup the dialogs

https://prismlibrary.com/docs/xamarin-forms/dialogs/styling-dialogs.html

But I can't find it in Prism.Maui. Is it not implemented yet ?

I was using the namespace xmlns:prism="http://prismlibrary.com"

**Comment by dansiegel** [comment]
Dialog Styling does exist. If you are having trouble please create a sample that reproduces the issue and we will reopen the issue.

**Comment by nikoslyk2093** [comment]
@dansiegel I use this namespace on xaml and DialogLayout does not exist

```
<?xml version="1.0" encoding="utf-8" ?>
<Frame x:Class="MyProject.Views.AddShoppingItemPopupPage"
       xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
       xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
       xmlns:prism="http://prismlibrary.com"
       xmlns:local="clr-namespace:MyProject.ViewModels;assembly=DailyOrganizer"
       x:Name="AddShoppingItemPopup"
       prism:DialogLayout.RelativeWidthRequest="0.5"
       prism:DialogLayout.RelativeHeightRequest="0.9"
       BackgroundColor="White">


    <StackLayout Orientation="Vertical">
        <Label Text="Description"/>
        <Entry Text="{Binding ShoppingItem.Name}"/>

        <Label Text="Quantity"/>
        <Entry Text="{Binding ShoppingItem.Quantity}"/>

        <Button Text="Insert" Command="{Binding InsertNewShoppingItemCommand}"/>
    </StackLayout>
</Frame>
```

**Comment by danielcodingpilot** [comment]
> (https://github.com/PrismLibrary/Prism.Maui/blob/master/src/Prism.Maui/Properties/AssemblyInfo.cs)

As a workaround (as you already might know), change the namespace declaration from
` xmlns:prism="http://prismlibrary.com"`
to
`xmlns:prism="clr-namespace:Prism.Services.Xaml;assembly=Prism.Maui"`

for an example see: https://github.com/danielcodingpilot/MauiPrismDialogService
