### ISSUE TITLE
iOS crash in Release mode build with AOT enabled

### ISSUE THREAD

**Issue by breenbob** [PrismLibrary/Prism.Maui#118]
### Description
I'm seeing a regression of [this issue](https://github.com/PrismLibrary/Prism/issues/1806) [fixed](https://github.com/PrismLibrary/Prism/commit/418b52ac391f34ebbe12ef772ddcfed57bd46e77) in the original Prism library when running a .Net Maui iOS app in release mode (i.e. with AOT enabled).

I suspect you are aware of this as the original fix is currently commented out in Prism.Maui:
![image](https://user-images.githubusercontent.com/6000851/207152772-c3ae5056-ec05-4ef5-aed6-e523ec20871f.png)

The docs on DryIoc [warned](https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/ResolutionPipeline.md#ruleswithoutfastexpressioncompiler) that this extension method is likely to be removed, and yup, [it has been](https://github.com/dadhi/DryIoc/commit/909233ad72039889fd1e6b22fd8e53c768084581) - over a year and a half ago - hence why the original fix had to be removed I assume?

Found [this](https://github.com/PrismLibrary/Prism/discussions/2715) saying a fix was coming to the main Prism library, but don't know if it made it or how it translates to Prism.Maui.

I am referencing Prism.DryIoc.Maui version 8.1.281-pre. 

### Expected Outcome

No Exception

### Actual Outcome

Following exception thrown causing the app to crash on a physical device.
```
Attempting to JIT compile method 
'FastExpressionCompiler.LightExpression.ExpressionCompiler:TryCompile (FastExpressionCompiler.LightExpression.ExpressionCompiler/ClosureInfo&,
    System.Type,System.Type[],
    System.Type,FastExpressionCompiler.LightExpression.Expression,
    System.Collections.Generic.IReadOnlyList`1<FastExpressionCompiler.LightExpression.ParameterExpression>,bool)' 
while running in aot-only mode. 
See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.
```

### Suggested Workarounds

As suggested in similar threads for similar issues (i.e. a jit compiler issue in sqlite-net-pcl with FastColumnSetter) I have tried enabling the mono interpreter using `<MtouchExtraArgs>--interpreter</MtouchExtraArgs>` in csproj Release configuration to allow jit compiler stuff to work, but this does not seem to resolve the issue for me, and isn't a long term solution anyway.

### Impact

This issue is a total blocker on iOS. I am aware this package is still experimental, and really appreciate all the great work in these packages, but this issue along with other issues around modal navigation are preventing us from using Prism in any meaningful way in our .Net Maui apps.

**Comment by dansiegel** [comment]
Can you please provide a sample that demonstrates the issue. While we appreciate that you've provided some relevant sample code there, we do not have time to create samples for everyone. If you have a sample that reproduces the issue we can re-open the issue.

Also note that this is an open source library and we do accept PRs so if this is indeed a bug and you would like to contribute a fix we would be happy to consider it.

**Comment by Matmork** [comment]
I was able to do a iOS release by adding this in MauiProgram.cs
`.UsePrism(DryIocContainerExtension.DefaultRules.WithUseInterpretation(), prism => ...`
