### ISSUE TITLE
Hey Dan we love prism but prism maui needs some love

### ISSUE THREAD

**Issue by gabsamples6** [PrismLibrary/Prism.Maui#119]
Hey,
We love prism and we would like to continue our Maui Journey using it - We really dont want to go down the route of shell or create our own navigation service and get it wrong.. 

Will you get time to give us an official version? any timelines...

**Comment by brzezinol** [comment]
I think community should donate this project since all of us uses it commercialy.

**Comment by gabsamples6** [comment]
I have to be honest here - Where I work it would be much easier if this would be a paid product rather than donation..

I dont think my company is willing to donate but If I went there to my account Dept and said . "We need this for mobile development and costs "$ a month or a year"  they would say yes no doubt!! 

@dansiegel  @brianlagunas  have you ever considered making this a paid product?  Lets be honest here , we all use it , we love that is free but these 2 guys have no time for giving the love and time to evolve this project at the speed we want.

Going back to the sponsorhip concept - I think it's easier for a company to paid a monthly or yearly subscription than - sponsor something.. This is how I see it ..

**Comment by dansiegel** [comment]
@gabsamples6 Prism does have an Enterprise Support option which does help fund the development of the project and make an impact on development priorities. 

Also just to be clear we haven't released Prism.Maui as stable because of bugs in Maui itself.

**Comment by gabsamples6** [comment]
@dansiegel personally that Model of support will not work and will be so hard for any company to pay for, but I hope I am wrong and works for you guys.

A product/ subscription  I.E like syncfusion etc.. it would not be a problem whatsoever to get signed off for purchase.


_"Also just to be clear we haven't released Prism.Maui as stable because of bugs in Maui itself."_

Maui is a total mess and full of bugs - but we have invested in MS tech stack and switch to Flutter etc.. would be very tough to sell to managment..   We want to move the app to MAUI somehow but we cannot do it without Prism.. with those navigation fixes...

Prism - I beleive they have fixed  https://github.com/dotnet/maui/issues/7275  related to #80
Some other people suggested fix  https://github.com/PrismLibrary/Prism.Maui/issues/106 and also there is a PR for modal 

I know you are busy but would you find time to give us another nuget?

Anyway for what is worth thank you

**Comment by brianlagunas** [comment]
Dan and I have spoken multiple times about changing the license for Prism and commercializing it. However, we never really came up with a good plan to make this happen while keeping our commitment to our awesome community. Maui has been holding us up for a long time now, and Prism for XF and WPF are stable. We do have some dependency updates we need to release, but we haven’t figured out our problem with moving to GitHub actions. Things are happening, just slowly and behind the scenes.

**Comment by dansiegel** [comment]
What @brianlagunas said... Also for what its worth, I am on trying to get out a .NET 7 release by end of year. But from what I am seeing we can still expect to see some hacks as MAUI itself still is plagued with issues that have not been fixed and may or may not be fixed before .NET 8.

**Comment by developer9969** [comment]
@brianlagunas @dansiegel  
First of all , thank you for supporting Prism!! Commercializing if you find the right price makes sense and I am sure that people/company will pay for it and given the number of downloads it should make it worth your while.

MAUI - they really cocked it up big time - but now we are stuck and somehow with lots of hacks we need to move to MAUI...
So Dan I really hope that you manage to give us something soon so that we can make at least start and make some progress..

**Comment by gabsamples6** [comment]
@brianlagunas thanks for your reply.. out of curiosity are you still writing mobile code ? any time for some video in the .net space? those were good..
I hope you and Dan can find the right balance and give us some prism update a bit more often :)

@dansiegel I hope you can manage to find time for an update on this nuget.  thanks again

**Comment by brianlagunas** [comment]
@gabsamples6 I am not currently writing mobile apps. My current projects have me in the web space working with React, Angular, Web Components, ASP.NET, Java, and Nodejs. I want to record more videos, but I just haven't had time. It can easily take 2 full days for a video, which just isn't doable for me right now.
