### ISSUE TITLE
Access the full URI in the GlobalNavigationObserver

### ISSUE THREAD

**Issue by berhir** [PrismLibrary/Prism.Maui#124]
With the GlobalNavigationObserver I have access to the requested navigation URI. For easier debugging, I would like to log the full navigation URI (the whole stack) after the new navigation happened.
Is this somehow possible?

**Comment by dansiegel** [comment]
The Navigation Observer fires AFTER the navigation request has completed. Any logging is on you.

**Comment by berhir** [comment]
Thank you for the quick reply. It's clear that I am responsible for the logging. My question was mainly how I can access the current full URI? As far as I understand, the `Uri` property of the `NavigationRequestContext` contains only the relative URI that was requested.
I understand that you can't add everything to the `NavigationRequestContext`. So I guess I must resolve a service to get the current navigation stack and the full URI.
Maybe you can point me in the right direction which service I have to resolve? Thank you!
