### ISSUE TITLE
Add support for Prism Dialogs

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism.Maui#21]
# Description

While some of the code is present the Prism DialogService needs to be fully ported and implemented for Prism.Maui

**Comment by HenJigg** [comment]
Do I need a Windows platform independent implementation for the dialog and navigation services? These in Xamarin.Forms they all seem to be different.

**Comment by HenJigg** [comment]
Dialog and Navigation Services, do I need a Windows platform independent implementation? These in Xamarin.Forms they all seem to be different.

**Comment by dansiegel** [comment]
Prism does not use Platform Specific implementations of anything with the exception that Prism.Forms does have some platform specific code to help with handling the Android Back Button
