### ISSUE TITLE
Migrate Navigation XAML Extensions

### ISSUE THREAD

**Issue by dansiegel** [PrismLibrary/Prism.Maui#22]
# Description

There are a number of XAML Extensions for Navigation such as the Navigate & GoBack Extensions which have not yet been ported over to MAUI. These need to be migrated over.

**Comment by chowarth** [comment]
Hi @dansiegel I've got a branch with these changes migrated across. I just need to double check that all the navigation parameter behaviour is working as expected, it should be, I've just not gone through it yet. I'm away for the next 3 weeks, is there any urgency on this being completed before then?

**Comment by dansiegel** [comment]
I won't say that there is a sense of urgency at this point. We can assign you the issue and you can get a PR in when you get a chance. Enjoy your holiday

**Comment by chowarth** [comment]
@dansiegel, I'm in the process of getting everything up-to-date with your recent changes and hopefully this will be good to go. One question I have though; In the navigation extensions there are a couple of methods that made use of `Xamarin.Forms.Internals.Log` and I'm unsure of what would be used as a replacement?

**Comment by dansiegel** [comment]
For now:
```cs
// TODO: Determine a good way to log
```
