### ISSUE TITLE
Setting the AutowireViewModel attached property of the ViewModelLocator to the value Disabled ends up in runtime error

### ISSUE THREAD

**Issue by egvijayanand** [PrismLibrary/Prism.Maui#58]
Setting the AutowireViewModel attached property of the ViewModelLocator to the value Disabled ends up in the below runtime error.

```xml
<ContentPage
    x:Class="MauiPrism.Views.MainPage"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:prism="http://prismlibrary.com"
    prism:ViewModelLocator.AutowireViewModel="Disabled">
<!-- User-defined content -->
</ContentPage>
```

'Unable to cast object of type 'Prism.Mvvm.ViewModelLocatorBehavior' to type 'System.Nullable`1[System.Boolean]'.'

**Comment by dansiegel** [comment]
Thanks for the bug report. You are absolutely correct. I've fixed this and it will be available in the Sponsor Connect feed shortly.
