### ISSUE TITLE
Why Error compiling Android/Windows  (Release) 	

### ISSUE THREAD

**Issue by gsgoodluck** [PrismLibrary/Prism.Maui#91]
XAGJS7004	System.ArgumentException: [已添加了具有相同键的项。]    在 System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)    在 System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)    在 Xamarin.Android.Tasks.TypeMapGenerator.GenerateRelease(Boolean skipJniAddNativeMethodRegistrationAttributeScan, List`1 javaTypes, String outputDirectory, ApplicationConfigTaskState appConfState)    在 Xamarin.Android.Tasks.GenerateJavaStubs.WriteTypeMappings(List`1 types, TypeDefinitionCache cache)    在 Xamarin.Android.Tasks.GenerateJavaStubs.Run(DirectoryAssemblyResolver res)    在 Xamarin.Android.Tasks.GenerateJavaStubs.RunTask()    在 Microsoft.Android.Build.Tasks.AndroidTask.Execute() 位置 /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:行号 17	MES	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.424\tools\Xamarin.Android.Common.targets	1442

#

Android Setting

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
	<application android:allowBackup="true" android:icon="@mipmap/appicon" android:roundIcon="@mipmap/appicon_round" android:usesCleartextTraffic="true" android:supportsRtl="true"></application>
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.INTERNET" />
</manifest>

Debug Mode   compiling NoError

**Comment by gsgoodluck** [comment]
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
	<application android:allowBackup="true" android:icon="@mipmap/appicon" android:roundIcon="@mipmap/appicon_round" android:usesCleartextTraffic="true" android:supportsRtl="true"></application>
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.INTERNET" />
</manifest>

**Comment by gsgoodluck** [comment]
: LineNo 1442
<GenerateJavaStubs  
      ResolvedAssemblies="@(_ResolvedAssemblies)"
      ResolvedUserAssemblies="@(_ResolvedUserMonoAndroidAssemblies)"
      ErrorOnCustomJavaObject="$(AndroidErrorOnCustomJavaObject)"
      ManifestTemplate="$(_AndroidManifestAbs)"
      MergedManifestDocuments="@(_MergedManifestDocuments)"
      Debug="$(AndroidIncludeDebugSymbols)"
      MultiDex="$(AndroidEnableMultiDex)"
      NeedsInternet="$(AndroidNeedsInternetPermission)"
      InstantRunEnabled="$(_InstantRunEnabled)"
      AndroidSdkPlatform="$(_AndroidApiLevel)"
      AndroidSdkDir="$(_AndroidSdkDirectory)"
      PackageName="$(_AndroidPackage)"
      VersionName="$(_AndroidVersionName)"
      VersionCode="$(_AndroidVersionCode)"
      ApplicationLabel="$(_ApplicationLabel)"
      ManifestPlaceholders="$(AndroidManifestPlaceholders)"
      OutputDirectory="$(IntermediateOutputPath)android"
      TypemapOutputDirectory="$(_NativeAssemblySourceDir)"
      GenerateNativeAssembly="!$(_InstantRunEnabled)"
      MergedAndroidManifestOutput="$(_ManifestOutput)"
      EmbedAssemblies="$(EmbedAssembliesIntoApk)"
      BundledWearApplicationName="$(BundledWearApplicationPackageName)"
      PackageNamingPolicy="$(AndroidPackageNamingPolicy)"
      ApplicationJavaClass="$(AndroidApplicationJavaClass)"
      FrameworkDirectories="$(_XATargetFrameworkDirectories);$(_XATargetFrameworkDirectories)Facades"
      AcwMapFile="$(_AcwMapFile)"
      SupportedAbis="@(_BuildTargetAbis)"
      SupportedOSPlatformVersion="$(SupportedOSPlatformVersion)"
      SkipJniAddNativeMethodRegistrationAttributeScan="$(_SkipJniAddNativeMethodRegistrationAttributeScan)"
      CheckedBuild="$(_AndroidCheckedBuild)">
    <Output TaskParameter="GeneratedBinaryTypeMaps" ItemName="_AndroidTypeMapping" Condition=" '$(_InstantRunEnabled)' == 'True' " />
  </GenerateJavaStubs>

**Comment by dansiegel** [comment]
Your issue is in your codebase. You've provided no reproduction and even if you did I would still most likely route you to the MAUI team (who would also need a sample reproduction) as what you've provided here doesn't show me an error with Prism. Also I happen to know that compiling a MAUI app with Prism.Maui in Release works just fine for Android, iOS, MacCatalyst, and Windows.

**Comment by gsgoodluck** [comment]
[Prism.Maui-master.zip](https://github.com/PrismLibrary/Prism.Maui/files/9135902/Prism.Maui-master.zip)
 Release 这个示例编译时发生同样的错误

**Comment by gsgoodluck** [comment]
Hi Change here

Prism.Maui.Rx

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>true</ImplicitUsings>
    <Description>Prism.Maui.Rx is a support package for .NET MAUI developers. This package provides some helpers to access an IObservable for globally handling Navigation Request Results.</Description>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Prism.Maui\Prism.Maui.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="6.0.0" />
    <PackageReference Include="System.Reactive" Version="5.0.0" />
  </ItemGroup>

</Project>


{
  "sdk": {
    "version": "6.0",
    "rollForward": "latestPatch",
    "allowPrerelease": true
  }
}
