### ISSUE TITLE
Cannot use SkiaSharp.Extended.UI.Maui to show Lottie animation

### ISSUE THREAD

**Issue by vulcanlee** [PrismLibrary/Prism.Maui#97]
I watch and follow this video [Implement Lottie Animations in .NET MAUI Under 10 Minutes!
](https://www.youtube.com/watch?v=o5X5yXdWpuc) that create .NET MAUI project, add a dotnetbot.json which is Lottie file and can work fine and can see Lottie animation on the App.

When I create MAUI project by [Prism .NET MAUI App (Dan Siegel)] template and do same things as above, I cannot see Lottie animation. But when I modify this project that does not use `.UsePrismApp<App>(PrismStartup.Configure)` method call and change to `.UseMauiApp<App>()`, the Lottie animation work fine.

Following is my test [video recording](https://vulcanfiles.blob.core.windows.net/$web/Share/2022/Prism.Maui%20Lottie%20Problem.mp4)

https://vulcanfiles.blob.core.windows.net/$web/Share/2022/Prism.Maui%20Lottie%20Problem.mp4

My test project source repo as following

https://github.com/vulcanlee/Prism-MAUI-Lottie

**Comment by dansiegel** [comment]
@mattleibow any ideas what could cause this?

**Comment by mattleibow** [comment]
What version of maui? The inital release had a bug with templated views.

**Comment by vulcanlee** [comment]
@mattleibow 

My environment is Visual Studio 2020 17.3 Preview 3.

I will upgrade my Visual Studio 2022 to 17.3 Preview 5 and retry this project.

**Comment by vulcanlee** [comment]
> I'll try and grab a copy of the repo this week, my first test will be to subscribe to the AnimationFailed and AnimationLoaded events of SKLottieView and see if either gets raised

@bijington 

I have subscribed to the AnimationFailed and AnimationLoaded events of SKLottieView and run this project on Android, the AnimationLoaded event will be fired and the AnimationFailed event will not be fired.

**Comment by vulcanlee** [comment]
Hi @mattleibow 

I just upgrade my Visual Studio 2022 to 17.3 Preview 5 and the Microsoft.Maui.Extensions and Microsoft.Maui.Dependencies NuGet version is 6.0.419

The SkiaSharp.Extended.UI.Maui NuGet version is 2.0.0-preview.59

When I run this project on Android emulator, cannot see Lottie animation on screen

**Comment by bijington** [comment]
@vulcanlee I have just had a play with your repo and found that you have one dependency that needed updating `Prism.DryIoc.Maui` after updating to the latest version `8.1.267-beta` I was able to view the animation on screen using the Prism based approach. I suspect that somewhere in the dependency tree it is pulling in a dependency on an older version of .NET MAUI (@mattleibow @dansiegel does this sound plausible?).

Can you try updating your project and see if that solves your issue?

Note that I am using Maui 6.0.424 and running on VS for Mac.

**Comment by bijington** [comment]
It may also be worth running

```bash
dotnet workload list
```

and observing what version of the maui workload you have. I had to run `dotnet workload update` in order to force an update of the maui workload. I think `dotnet workload install maui` should also do it if you only want to update that one workload

**Comment by vulcanlee** [comment]
> `Prism.DryIoc.Maui` after updating to the latest version `8.1.267-beta`

@bijington 

I do following cli to update my MAUI to latest  version

dotnet workload update


dotnet workload list

maui                  6.0.424/6.0.400       SDK 6.0.400
runtimes-windows      6.0.7/6.0.300         VS 17.3.32721.290
maui-ios              6.0.424/6.0.400       VS 17.3.32721.290
maui-android          6.0.424/6.0.400       VS 17.3.32721.290
android               32.0.440/6.0.300      VS 17.3.32721.290
maccatalyst           15.4.442/6.0.400      VS 17.3.32721.290
ios                   15.4.442/6.0.400      VS 17.3.32721.290
maui-windows          6.0.424/6.0.400       VS 17.3.32721.290
maui-maccatalyst      6.0.424/6.0.400       VS 17.3.32721.290

But I cannot update Prism.DryIoc.Maui to the latest version 8.1.267-beta 
I only can update to 8.1.254-beta
![image](https://user-images.githubusercontent.com/5071744/182392823-e50e3860-4161-4a23-a11d-9a11823f201d.png)


It is awesome, I can see the Lottie animation

![image](https://user-images.githubusercontent.com/5071744/182392984-5b1bd20b-4c7d-40b6-ab93-dcda6ac97813.png)


Thanks for your help.
