### ISSUE TITLE
Suggestion: Prism Maui  removing Boilerplate  commands + properties

### ISSUE THREAD

**Issue by developer9969** [PrismLibrary/Prism.Maui#99]
Hi Dan,
Big fan of prism and the navigation service is the best there is , however I find quite appealing the use of MVVM toolkit especially the ability not to have boilerplates commands etc... using source generators

Do you think you would consider introducing something along those lines for prism Maui. I think that is missing link and what everyone is talking about and jumping on the MVVM toolkit bandwagon.

Great work!

**Comment by dansiegel** [comment]
@developer9969 I'm not sure exactly what you're looking for but a couple quick notes... something like this is better suited as a discussion in the Prism repo.
Also if you use the Community Toolkit and not Prism you lose out on everything that Prism offers you. But if you use Prism for it's Navigation, Dialogs, Regions, Modules etc... you can still use 3rd party libraries like ReactiveUI or the Community Toolkit for your ViewModel's base class or for your Commands.
